# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=256)),
                ('nom_famille', models.CharField(max_length=256)),
                ('date_birth', models.DateField()),
                ('sexe', models.CharField(max_length=256)),
                ('nationalite', models.CharField(max_length=256)),
                ('email_adresse', models.CharField(max_length=256)),
                ('facebook', models.CharField(max_length=256)),
                ('arrivee_date', models.DateField()),
                ('depart_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=256)),
                ('categorie', models.CharField(max_length=256)),
                ('prix', models.PositiveIntegerField()),
                ('prix_special', models.PositiveIntegerField()),
                ('nbr_place', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='produit',
            field=models.ManyToManyField(to='booking.Produit'),
        ),
    ]
