# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='produit',
        ),
        migrations.AddField(
            model_name='client',
            name='produit',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Tuba', 'Tuba'), ('Plongée', 'Plongée')], default='null', max_length=256),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], max_length=10),
        ),
    ]
