# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20180314_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='produit',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='booking.Produit'),
        ),
    ]
